version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pw"
      CSV_FILENAME: "data.csv"
    ports: 
      - 5432:5432
  manager:
    build: .
    depends_on: 
      - db
    links:
      - db

